
@startuml
'autonumber
actor       Actor       as User
participant UI
participant BackEnd
database    Database    as Db

User -> UI ++: enter username
User -> UI : enter password
User -> UI : submit form
UI->UI:Display processing status
UI ->> BackEnd --++ : user NP
note left: NP = name & password

BackEnd -> Db ++ : find User
Db --> BackEnd -- : user Result
BackEnd -> BackEnd: process user details

alt #lightgreen user found
    BackEnd -->> UI --++: user details
    UI -[#aqua]> UI: remember user details
    note left #aqua
    temporary solution
    (will be replaced with cookie,etc)
    end note
    UI -> UI : replace login view with logout button
    UI -> UI : update css classes based on user role
    UI ->> BackEnd : request quizzes
    note right: see "request quizzes" flow

else #pink user not found
    BackEnd -->> UI --: user not found
    UI -> UI: incorrect credentials, try again
end
@enduml
